export const GET_ERRORS = "GET_ERRORS";
export const CENTRE_LOADING = "CENTRE_LOADING";
export const SET_CURRENT_CENTRE = "SET_CURRENT_CENTRE";

export const GET_ERRORS_CLIENT = "GET_ERRORS";
export const CLIENT_LOADING = "CLIENT_LOADING";
export const SET_CURRENT_CLIENT = "SET_CURRENT_CLIENT";
