export const GET_ERRORS = "GET_ERRORS";
export const CENTRE_LOADING = "CENTRE_LOADING";
export const SET_CURRENT_CENTRE = "SET_CURRENT_CENTRE";

/* export const CENTRE_LOADING = "USER_LOADING";
export const SET_CURRENT_CENTRE = "SET_CURRENT_USER"; */